### ISSUE TITLE
Limit number of cores/threads used

### ISSUE THREAD

**Issue by mherkhachatryan** [PolyChord/PolyChordLite#114]
How can one limit of number of cores or threads used by polychord. I have tried to to set with `OMP_NUM_THREADS` environmental variable inside docker, but it does not seem to help. 

Any help would be appreciated.

**Comment by mherkhachatryan** [comment]
I deployed polychord inside docker container, limit container usage with this docker-compose command
```
    deploy:
      resources:
        limits:
          cpus: '3.0'
```
it's running 2nd day, but on multinest inside same environment sampling would take on same number of data points and parameters like 40 minutes.
